title: Melânia Pereira
logo: /assets/img/logo.jpg
favicon: /assets/img/logo.jpg
description: Hello, I'm Melânia Pereira and this is my website. Here you can find everything about my work.
google_analytics:
theme: jekyll-theme-minimal